Update documentation
sixlettervariables/csnats pull request #4
Opened 2017-07-05 21:26 UTC by sixlettervariables

Adds XML documentation.

2017-07-10 15:20 UTC, ColinSullivan1 requested changes
Great work here, really polishes up the doc.  Much appreciated!

2017-07-10 15:20 UTC, ColinSullivan1 commented on NATS.Client/AsyncSub.cs
> +    /// <see cref="AsyncSubscription"/> asynchronously delivers messages to listeners of the <see cref="MessageHandler"/>
Can you add a note that this class shouldn't be used directly - to instead use the interface.

2017-07-10 15:20 UTC, ColinSullivan1 commented on NATS.Client/Conn.cs
>      public enum ConnState
Thanks, I missed these!

2017-07-10 15:20 UTC, ColinSullivan1 commented on NATS.Client/Subscription.cs
>      public class Subscription : ISubscription, IDisposable
Maybe add a comment to use ISubscription instead?

2017-07-10 15:23 UTC, ColinSullivan1 commented
BTW - Doxygen found some issues; these were from running  build_doc.bat in the `<src>/documentation` directory.  I've attached output.

[doxyout.txt](https://github.com/sixlettervariables/csnats/files/1136027/doxyout.txt)

2017-07-11 14:52 UTC, sixlettervariables commented
It appears doxygen does not handle `<see langword="">`. I'll replace these with something it supports.

2017-07-11 19:25 UTC, ColinSullivan1 commented on NATS.Client/Subscription.cs
> +            GC.SuppressFinalize(this);
+1

2017-07-11 19:26 UTC, ColinSullivan1 approved these changes
I've spot checked these, and they look great.  Great addition to the NATS client.  Thanks for all of the work!

2017-09-22 13:21 UTC, merged